"""init schema

Revision ID: 95a07b9f83f8
Revises: 
Create Date: 2026-03-10 10:46:00.335592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a07b9f83f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'name', name='uq_district_region_name')
    )
    op.create_index(op.f('ix_districts_region_id'), 'districts', ['region_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('settlement', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name', name='uq_school_district_name')
    )
    op.create_index(op.f('ix_schools_district_id'), 'schools', ['district_id'], unique=False)
    op.create_index(op.f('ix_schools_settlement'), 'schools', ['settlement'], unique=False)
    op.create_table('school_staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('academic_degree', sa.String(length=255), nullable=True),
    sa.Column('position_text', sa.Text(), nullable=True),
    sa.Column('university', sa.Text(), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('diploma_no', sa.String(length=64), nullable=True),
    sa.Column('diploma_specialty', sa.Text(), nullable=True),
    sa.Column('study_type', sa.Text(), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('ped_start_date', sa.Date(), nullable=True),
    sa.Column('total_experience_years', sa.Integer(), nullable=True),
    sa.Column('ped_experience_years', sa.Integer(), nullable=True),
    sa.Column('qualification_category', sa.Text(), nullable=True),
    sa.Column('qualification_order_no', sa.String(length=64), nullable=True),
    sa.Column('qualification_order_date', sa.Date(), nullable=True),
    sa.Column('attestation_date', sa.Date(), nullable=True),
    sa.Column('reattestation_date', sa.Date(), nullable=True),
    sa.Column('course_passed_date', sa.Date(), nullable=True),
    sa.Column('course_due_date', sa.Date(), nullable=True),
    sa.Column('course_place', sa.Text(), nullable=True),
    sa.Column('course_certificate_no', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('creative_topic', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'iin', name='uq_staff_school_iin')
    )
    op.create_index(op.f('ix_school_staff_members_is_active'), 'school_staff_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_school_staff_members_ped_start_date'), 'school_staff_members', ['ped_start_date'], unique=False)
    op.create_index(op.f('ix_school_staff_members_qualification_order_date'), 'school_staff_members', ['qualification_order_date'], unique=False)
    op.create_index(op.f('ix_school_staff_members_school_id'), 'school_staff_members', ['school_id'], unique=False)
    op.create_index('ix_staff_iin', 'school_staff_members', ['iin'], unique=False)
    op.create_index('ix_staff_school_id', 'school_staff_members', ['school_id'], unique=False)
    op.create_table('school_staff_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('director', 'd_otijo', 'd_oijo', 'd_tijo', 'd_oajo', 'd_bozho', 'd_shizho', 'aed_to', 'pu', 'qbbp', 'pkbb', 'abj', 'ap', 'sj', 'uj', 'ped_psy', 'defectologist', 'librarian', 'sch_nurs', 'guide', name='responsible_role_enum'), nullable=False),
    sa.Column('role_context', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['school_staff_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superuser', 'region_admin', 'region_staff', 'district_admin', 'district_staff', 'school_admin', 'school_staff', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('eds_enabled', sa.Boolean(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('staff_member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('\n            (\n                (CASE WHEN region_id IS NULL THEN 0 ELSE 1 END) +\n                (CASE WHEN district_id IS NULL THEN 0 ELSE 1 END) +\n                (CASE WHEN school_id IS NULL THEN 0 ELSE 1 END)\n            ) <= 1\n            ', name='ck_users_single_scope'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['school_staff_members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_iin'), 'users', ['iin'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_region_id'), 'users', ['region_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_index(op.f('ix_users_staff_member_id'), 'users', ['staff_member_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('plan_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.Text(), nullable=False),
    sa.Column('full_title', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_title', name='uq_plan_directions_short_title')
    )
    op.create_index('ix_plan_directions_active_sort', 'plan_directions', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_plan_directions_created_at'), 'plan_directions', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_directions_created_by_user_id'), 'plan_directions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_plan_directions_is_active'), 'plan_directions', ['is_active'], unique=False)
    op.create_index(op.f('ix_plan_directions_sort_order'), 'plan_directions', ['sort_order'], unique=False)
    op.create_table('plan_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('academic_year', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_templates_active_year', 'plan_templates', ['is_active', 'academic_year'], unique=False)
    op.create_index(op.f('ix_plan_templates_created_at'), 'plan_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_templates_created_by_user_id'), 'plan_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_plan_templates_is_active'), 'plan_templates', ['is_active'], unique=False)
    op.create_table('registration_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('target_role', sa.Enum('superuser', 'region_admin', 'region_staff', 'district_admin', 'district_staff', 'school_admin', 'school_staff', name='user_role'), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quota_total', sa.Integer(), nullable=False),
    sa.Column('quota_left', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('\n            (\n                (CASE WHEN region_id IS NULL THEN 0 ELSE 1 END) +\n                (CASE WHEN district_id IS NULL THEN 0 ELSE 1 END) +\n                (CASE WHEN school_id IS NULL THEN 0 ELSE 1 END)\n            ) <= 1\n            ', name='ck_codes_single_scope'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_codes_code_lookup_hash'), 'registration_codes', ['code_lookup_hash'], unique=True)
    op.create_index('ix_registration_codes_issued_by', 'registration_codes', ['issued_by_user_id'], unique=False)
    op.create_table('plan_template_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_override', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['plan_directions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['plan_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'direction_id', name='uq_tpl_direction')
    )
    op.create_index(op.f('ix_plan_template_directions_created_at'), 'plan_template_directions', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_template_directions_direction_id'), 'plan_template_directions', ['direction_id'], unique=False)
    op.create_index(op.f('ix_plan_template_directions_sort_order'), 'plan_template_directions', ['sort_order'], unique=False)
    op.create_index(op.f('ix_plan_template_directions_template_id'), 'plan_template_directions', ['template_id'], unique=False)
    op.create_index('ix_tpldir_template_sort', 'plan_template_directions', ['template_id', 'sort_order'], unique=False)
    op.create_table('registration_code_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['registration_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_uses_code_id', 'registration_code_uses', ['code_id'], unique=False)
    op.create_index('ix_code_uses_used_by', 'registration_code_uses', ['used_by_user_id'], unique=False)
    op.create_table('school_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['plan_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year', name='uq_school_plans_school_year')
    )
    op.create_index(op.f('ix_school_plans_academic_year'), 'school_plans', ['academic_year'], unique=False)
    op.create_index(op.f('ix_school_plans_created_at'), 'school_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_school_plans_school_id'), 'school_plans', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_plans_status'), 'school_plans', ['status'], unique=False)
    op.create_index(op.f('ix_school_plans_template_id'), 'school_plans', ['template_id'], unique=False)
    op.create_table('plan_template_rows_11',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_direction_id', sa.Integer(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('control_object', sa.Text(), nullable=True),
    sa.Column('control_type', sa.Text(), nullable=True),
    sa.Column('methods', sa.Text(), nullable=True),
    sa.Column('deadlines', sa.Text(), nullable=True),
    sa.Column('responsibles', sa.Text(), nullable=True),
    sa.Column('review_place', sa.Text(), nullable=True),
    sa.Column('management_decision', sa.Text(), nullable=True),
    sa.Column('second_control', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_direction_id'], ['plan_template_directions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_direction_id', 'row_order', name='uq_tpldir_row11_order')
    )
    op.create_index(op.f('ix_plan_template_rows_11_created_at'), 'plan_template_rows_11', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_template_rows_11_row_order'), 'plan_template_rows_11', ['row_order'], unique=False)
    op.create_index(op.f('ix_plan_template_rows_11_template_direction_id'), 'plan_template_rows_11', ['template_direction_id'], unique=False)
    op.create_index('ix_row11_tpldir_order', 'plan_template_rows_11', ['template_direction_id', 'row_order'], unique=False)
    op.create_table('plan_template_rows_4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_direction_id', sa.Integer(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('no', sa.Text(), nullable=True),
    sa.Column('control_object', sa.Text(), nullable=False),
    sa.Column('risk_text', sa.Text(), nullable=True),
    sa.Column('decision_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_direction_id'], ['plan_template_directions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_direction_id', 'row_order', name='uq_tpldir_row4_order')
    )
    op.create_index(op.f('ix_plan_template_rows_4_created_at'), 'plan_template_rows_4', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_template_rows_4_row_order'), 'plan_template_rows_4', ['row_order'], unique=False)
    op.create_index(op.f('ix_plan_template_rows_4_template_direction_id'), 'plan_template_rows_4', ['template_direction_id'], unique=False)
    op.create_index('ix_row4_tpldir_order', 'plan_template_rows_4', ['template_direction_id', 'row_order'], unique=False)
    op.create_table('school_month_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_plan_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='plan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(month BETWEEN 9 AND 12) OR (month BETWEEN 1 AND 5)', name='ck_school_month_plans_month_range'),
    sa.ForeignKeyConstraint(['school_plan_id'], ['school_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_plan_id', 'year', 'month', name='uq_school_month_plan_school_plan_year_month')
    )
    op.create_index(op.f('ix_school_month_plans_created_at'), 'school_month_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_school_month_plans_month'), 'school_month_plans', ['month'], unique=False)
    op.create_index('ix_school_month_plans_plan_year_month_status', 'school_month_plans', ['school_plan_id', 'year', 'month', 'status'], unique=False)
    op.create_index(op.f('ix_school_month_plans_school_plan_id'), 'school_month_plans', ['school_plan_id'], unique=False)
    op.create_index(op.f('ix_school_month_plans_status'), 'school_month_plans', ['status'], unique=False)
    op.create_index(op.f('ix_school_month_plans_year'), 'school_month_plans', ['year'], unique=False)
    op.create_table('school_plan_rows_11',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_plan_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('control_object', sa.Text(), nullable=True),
    sa.Column('control_type', sa.Text(), nullable=True),
    sa.Column('methods', sa.Text(), nullable=True),
    sa.Column('deadlines', sa.Text(), nullable=True),
    sa.Column('responsibles', sa.Text(), nullable=True),
    sa.Column('review_place', sa.Text(), nullable=True),
    sa.Column('management_decision', sa.Text(), nullable=True),
    sa.Column('second_control', sa.Text(), nullable=True),
    sa.Column('period_type', sa.Enum('month', 'months', 'monthly', 'quarter', 'all_year', name='plan_period_type'), nullable=False),
    sa.Column('period_value_int', sa.Integer(), nullable=True),
    sa.Column('period_values', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['plan_directions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_plan_id'], ['school_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_plan_id', 'direction_id', 'row_order', name='uq_school_rows11_plan_dir_order')
    )
    op.create_index(op.f('ix_school_plan_rows_11_direction_id'), 'school_plan_rows_11', ['direction_id'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_11_is_custom'), 'school_plan_rows_11', ['is_custom'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_11_period_type'), 'school_plan_rows_11', ['period_type'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_11_period_value_int'), 'school_plan_rows_11', ['period_value_int'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_11_row_order'), 'school_plan_rows_11', ['row_order'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_11_school_plan_id'), 'school_plan_rows_11', ['school_plan_id'], unique=False)
    op.create_table('school_plan_rows_4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_plan_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('no', sa.Text(), nullable=True),
    sa.Column('control_object', sa.Text(), nullable=False),
    sa.Column('risk_text', sa.Text(), nullable=True),
    sa.Column('decision_text', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('responsible_role', sa.Enum('director', 'd_otijo', 'd_oijo', 'd_tijo', 'd_oajo', 'd_bozho', 'd_shizho', 'aed_to', 'pu', 'qbbp', 'pkbb', 'abj', 'ap', 'sj', 'uj', 'ped_psy', 'defectologist', 'librarian', 'sch_nurs', 'guide', name='responsible_role_enum'), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['plan_directions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_plan_id'], ['school_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_plan_id', 'direction_id', 'row_order', name='uq_school_rows4_plan_dir_order')
    )
    op.create_index(op.f('ix_school_plan_rows_4_direction_id'), 'school_plan_rows_4', ['direction_id'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_4_is_custom'), 'school_plan_rows_4', ['is_custom'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_4_responsible_role'), 'school_plan_rows_4', ['responsible_role'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_4_responsible_user_id'), 'school_plan_rows_4', ['responsible_user_id'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_4_row_order'), 'school_plan_rows_4', ['row_order'], unique=False)
    op.create_index(op.f('ix_school_plan_rows_4_school_plan_id'), 'school_plan_rows_4', ['school_plan_id'], unique=False)
    op.create_table('school_month_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_plan_id', sa.Integer(), nullable=False),
    sa.Column('source_row11_id', sa.Integer(), nullable=True),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('week_of_month', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', 'not_applicable', name='plan_item_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responsible_role', sa.Enum('director', 'd_otijo', 'd_oijo', 'd_tijo', 'd_oajo', 'd_bozho', 'd_shizho', 'aed_to', 'pu', 'qbbp', 'pkbb', 'abj', 'ap', 'sj', 'uj', 'ped_psy', 'defectologist', 'librarian', 'sch_nurs', 'guide', name='responsible_role_enum'), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.CheckConstraint('planned_end IS NULL OR planned_start IS NULL OR planned_end >= planned_start', name='ck_month_plan_item_date_range'),
    sa.CheckConstraint('week_of_month IS NULL OR (week_of_month >= 1 AND week_of_month <= 6)', name='ck_month_plan_item_week_range'),
    sa.ForeignKeyConstraint(['month_plan_id'], ['school_month_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_row11_id'], ['school_plan_rows_11.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_plan_id', 'source_row11_id', name='uq_month_plan_item_unique_source')
    )
    op.create_index('ix_month_plan_items_plan_dates', 'school_month_plan_items', ['month_plan_id', 'planned_start', 'planned_end'], unique=False)
    op.create_index('ix_month_plan_items_plan_included_week', 'school_month_plan_items', ['month_plan_id', 'is_included', 'week_of_month'], unique=False)
    op.create_index('ix_month_plan_items_source_status', 'school_month_plan_items', ['source_row11_id', 'status'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_created_at'), 'school_month_plan_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_is_included'), 'school_month_plan_items', ['is_included'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_month_plan_id'), 'school_month_plan_items', ['month_plan_id'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_planned_end'), 'school_month_plan_items', ['planned_end'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_planned_start'), 'school_month_plan_items', ['planned_start'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_responsible_role'), 'school_month_plan_items', ['responsible_role'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_responsible_user_id'), 'school_month_plan_items', ['responsible_user_id'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_source_row11_id'), 'school_month_plan_items', ['source_row11_id'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_status'), 'school_month_plan_items', ['status'], unique=False)
    op.create_index(op.f('ix_school_month_plan_items_week_of_month'), 'school_month_plan_items', ['week_of_month'], unique=False)
    op.create_table('school_plan_row11_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row11_id', sa.Integer(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['row11_id'], ['school_plan_rows_11.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['school_staff_members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row11_id', 'staff_member_id', name='uq_row11_staff_member')
    )
    op.create_index('ix_row11_assignee_row11_id', 'school_plan_row11_assignees', ['row11_id'], unique=False)
    op.create_index('ix_row11_assignee_staff_member_id', 'school_plan_row11_assignees', ['staff_member_id'], unique=False)
    op.create_index('ix_row11_assignee_staff_row11', 'school_plan_row11_assignees', ['staff_member_id', 'row11_id'], unique=False)
    op.create_index(op.f('ix_school_plan_row11_assignees_assigned_by_user_id'), 'school_plan_row11_assignees', ['assigned_by_user_id'], unique=False)
    op.create_table('school_plan_row11_responsibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row11_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('director', 'd_otijo', 'd_oijo', 'd_tijo', 'd_oajo', 'd_bozho', 'd_shizho', 'aed_to', 'pu', 'qbbp', 'pkbb', 'abj', 'ap', 'sj', 'uj', 'ped_psy', 'defectologist', 'librarian', 'sch_nurs', 'guide', name='responsible_role_enum'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['row11_id'], ['school_plan_rows_11.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row11_id', 'role', name='uq_row11_role')
    )
    op.create_index('ix_row11_resp_role', 'school_plan_row11_responsibles', ['role'], unique=False)
    op.create_index('ix_row11_resp_row11_id', 'school_plan_row11_responsibles', ['row11_id'], unique=False)
    op.create_index('ix_row11_resp_row11_role', 'school_plan_row11_responsibles', ['row11_id', 'role'], unique=False)
    op.create_table('school_plan_row_11_required_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row11_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('plan', 'protocol', 'act', 'report', 'reference', 'other', name='document_type'), nullable=False),
    sa.ForeignKeyConstraint(['row11_id'], ['school_plan_rows_11.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row11_id', 'document_type', name='uq_row11_required_document_type')
    )
    op.create_index(op.f('ix_school_plan_row_11_required_documents_document_type'), 'school_plan_row_11_required_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_school_plan_row_11_required_documents_row11_id'), 'school_plan_row_11_required_documents', ['row11_id'], unique=False)
    op.create_table('school_plan_row_11_review_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row11_id', sa.Integer(), nullable=False),
    sa.Column('review_place', sa.Enum('ped_council', 'method_council', 'director_council', 'administrative_council', 'method_assoc', name='review_place'), nullable=False),
    sa.ForeignKeyConstraint(['row11_id'], ['school_plan_rows_11.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row11_id', 'review_place', name='uq_row11_review_place')
    )
    op.create_index(op.f('ix_school_plan_row_11_review_places_review_place'), 'school_plan_row_11_review_places', ['review_place'], unique=False)
    op.create_index(op.f('ix_school_plan_row_11_review_places_row11_id'), 'school_plan_row_11_review_places', ['row11_id'], unique=False)
    op.create_table('school_month_plan_item_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_item_id', sa.Integer(), nullable=False),
    sa.Column('staff_role_id', sa.Integer(), nullable=False),
    sa.Column('assignment_kind', sa.Enum('primary', 'co_executor', name='assignment_kind_enum'), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['month_item_id'], ['school_month_plan_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_role_id'], ['school_staff_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_item_id', 'staff_role_id', name='uq_month_item_assignee_role')
    )
    op.create_index('ix_month_item_assignee_staff_role', 'school_month_plan_item_assignees', ['staff_role_id'], unique=False)
    op.create_index(op.f('ix_school_month_plan_item_assignees_assignment_kind'), 'school_month_plan_item_assignees', ['assignment_kind'], unique=False)
    op.create_index(op.f('ix_school_month_plan_item_assignees_month_item_id'), 'school_month_plan_item_assignees', ['month_item_id'], unique=False)
    op.create_index(op.f('ix_school_month_plan_item_assignees_staff_role_id'), 'school_month_plan_item_assignees', ['staff_role_id'], unique=False)
    op.create_table('school_month_plan_item_review_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_item_id', sa.Integer(), nullable=False),
    sa.Column('review_place', sa.Enum('ped_council', 'method_council', 'director_council', 'administrative_council', 'method_assoc', name='review_place'), nullable=False),
    sa.ForeignKeyConstraint(['month_item_id'], ['school_month_plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_item_id', 'review_place', name='uq_month_item_review_place')
    )
    op.create_index(op.f('ix_school_month_plan_item_review_places_month_item_id'), 'school_month_plan_item_review_places', ['month_item_id'], unique=False)
    op.create_index(op.f('ix_school_month_plan_item_review_places_review_place'), 'school_month_plan_item_review_places', ['review_place'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_month_plan_item_review_places_review_place'), table_name='school_month_plan_item_review_places')
    op.drop_index(op.f('ix_school_month_plan_item_review_places_month_item_id'), table_name='school_month_plan_item_review_places')
    op.drop_table('school_month_plan_item_review_places')
    op.drop_index(op.f('ix_school_month_plan_item_assignees_staff_role_id'), table_name='school_month_plan_item_assignees')
    op.drop_index(op.f('ix_school_month_plan_item_assignees_month_item_id'), table_name='school_month_plan_item_assignees')
    op.drop_index(op.f('ix_school_month_plan_item_assignees_assignment_kind'), table_name='school_month_plan_item_assignees')
    op.drop_index('ix_month_item_assignee_staff_role', table_name='school_month_plan_item_assignees')
    op.drop_table('school_month_plan_item_assignees')
    op.drop_index(op.f('ix_school_plan_row_11_review_places_row11_id'), table_name='school_plan_row_11_review_places')
    op.drop_index(op.f('ix_school_plan_row_11_review_places_review_place'), table_name='school_plan_row_11_review_places')
    op.drop_table('school_plan_row_11_review_places')
    op.drop_index(op.f('ix_school_plan_row_11_required_documents_row11_id'), table_name='school_plan_row_11_required_documents')
    op.drop_index(op.f('ix_school_plan_row_11_required_documents_document_type'), table_name='school_plan_row_11_required_documents')
    op.drop_table('school_plan_row_11_required_documents')
    op.drop_index('ix_row11_resp_row11_role', table_name='school_plan_row11_responsibles')
    op.drop_index('ix_row11_resp_row11_id', table_name='school_plan_row11_responsibles')
    op.drop_index('ix_row11_resp_role', table_name='school_plan_row11_responsibles')
    op.drop_table('school_plan_row11_responsibles')
    op.drop_index(op.f('ix_school_plan_row11_assignees_assigned_by_user_id'), table_name='school_plan_row11_assignees')
    op.drop_index('ix_row11_assignee_staff_row11', table_name='school_plan_row11_assignees')
    op.drop_index('ix_row11_assignee_staff_member_id', table_name='school_plan_row11_assignees')
    op.drop_index('ix_row11_assignee_row11_id', table_name='school_plan_row11_assignees')
    op.drop_table('school_plan_row11_assignees')
    op.drop_index(op.f('ix_school_month_plan_items_week_of_month'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_status'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_source_row11_id'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_responsible_user_id'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_responsible_role'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_planned_start'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_planned_end'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_month_plan_id'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_is_included'), table_name='school_month_plan_items')
    op.drop_index(op.f('ix_school_month_plan_items_created_at'), table_name='school_month_plan_items')
    op.drop_index('ix_month_plan_items_source_status', table_name='school_month_plan_items')
    op.drop_index('ix_month_plan_items_plan_included_week', table_name='school_month_plan_items')
    op.drop_index('ix_month_plan_items_plan_dates', table_name='school_month_plan_items')
    op.drop_table('school_month_plan_items')
    op.drop_index(op.f('ix_school_plan_rows_4_school_plan_id'), table_name='school_plan_rows_4')
    op.drop_index(op.f('ix_school_plan_rows_4_row_order'), table_name='school_plan_rows_4')
    op.drop_index(op.f('ix_school_plan_rows_4_responsible_user_id'), table_name='school_plan_rows_4')
    op.drop_index(op.f('ix_school_plan_rows_4_responsible_role'), table_name='school_plan_rows_4')
    op.drop_index(op.f('ix_school_plan_rows_4_is_custom'), table_name='school_plan_rows_4')
    op.drop_index(op.f('ix_school_plan_rows_4_direction_id'), table_name='school_plan_rows_4')
    op.drop_table('school_plan_rows_4')
    op.drop_index(op.f('ix_school_plan_rows_11_school_plan_id'), table_name='school_plan_rows_11')
    op.drop_index(op.f('ix_school_plan_rows_11_row_order'), table_name='school_plan_rows_11')
    op.drop_index(op.f('ix_school_plan_rows_11_period_value_int'), table_name='school_plan_rows_11')
    op.drop_index(op.f('ix_school_plan_rows_11_period_type'), table_name='school_plan_rows_11')
    op.drop_index(op.f('ix_school_plan_rows_11_is_custom'), table_name='school_plan_rows_11')
    op.drop_index(op.f('ix_school_plan_rows_11_direction_id'), table_name='school_plan_rows_11')
    op.drop_table('school_plan_rows_11')
    op.drop_index(op.f('ix_school_month_plans_year'), table_name='school_month_plans')
    op.drop_index(op.f('ix_school_month_plans_status'), table_name='school_month_plans')
    op.drop_index(op.f('ix_school_month_plans_school_plan_id'), table_name='school_month_plans')
    op.drop_index('ix_school_month_plans_plan_year_month_status', table_name='school_month_plans')
    op.drop_index(op.f('ix_school_month_plans_month'), table_name='school_month_plans')
    op.drop_index(op.f('ix_school_month_plans_created_at'), table_name='school_month_plans')
    op.drop_table('school_month_plans')
    op.drop_index('ix_row4_tpldir_order', table_name='plan_template_rows_4')
    op.drop_index(op.f('ix_plan_template_rows_4_template_direction_id'), table_name='plan_template_rows_4')
    op.drop_index(op.f('ix_plan_template_rows_4_row_order'), table_name='plan_template_rows_4')
    op.drop_index(op.f('ix_plan_template_rows_4_created_at'), table_name='plan_template_rows_4')
    op.drop_table('plan_template_rows_4')
    op.drop_index('ix_row11_tpldir_order', table_name='plan_template_rows_11')
    op.drop_index(op.f('ix_plan_template_rows_11_template_direction_id'), table_name='plan_template_rows_11')
    op.drop_index(op.f('ix_plan_template_rows_11_row_order'), table_name='plan_template_rows_11')
    op.drop_index(op.f('ix_plan_template_rows_11_created_at'), table_name='plan_template_rows_11')
    op.drop_table('plan_template_rows_11')
    op.drop_index(op.f('ix_school_plans_template_id'), table_name='school_plans')
    op.drop_index(op.f('ix_school_plans_status'), table_name='school_plans')
    op.drop_index(op.f('ix_school_plans_school_id'), table_name='school_plans')
    op.drop_index(op.f('ix_school_plans_created_at'), table_name='school_plans')
    op.drop_index(op.f('ix_school_plans_academic_year'), table_name='school_plans')
    op.drop_table('school_plans')
    op.drop_index('ix_code_uses_used_by', table_name='registration_code_uses')
    op.drop_index('ix_code_uses_code_id', table_name='registration_code_uses')
    op.drop_table('registration_code_uses')
    op.drop_index('ix_tpldir_template_sort', table_name='plan_template_directions')
    op.drop_index(op.f('ix_plan_template_directions_template_id'), table_name='plan_template_directions')
    op.drop_index(op.f('ix_plan_template_directions_sort_order'), table_name='plan_template_directions')
    op.drop_index(op.f('ix_plan_template_directions_direction_id'), table_name='plan_template_directions')
    op.drop_index(op.f('ix_plan_template_directions_created_at'), table_name='plan_template_directions')
    op.drop_table('plan_template_directions')
    op.drop_index('ix_registration_codes_issued_by', table_name='registration_codes')
    op.drop_index(op.f('ix_registration_codes_code_lookup_hash'), table_name='registration_codes')
    op.drop_table('registration_codes')
    op.drop_index(op.f('ix_plan_templates_is_active'), table_name='plan_templates')
    op.drop_index(op.f('ix_plan_templates_created_by_user_id'), table_name='plan_templates')
    op.drop_index(op.f('ix_plan_templates_created_at'), table_name='plan_templates')
    op.drop_index('ix_plan_templates_active_year', table_name='plan_templates')
    op.drop_table('plan_templates')
    op.drop_index(op.f('ix_plan_directions_sort_order'), table_name='plan_directions')
    op.drop_index(op.f('ix_plan_directions_is_active'), table_name='plan_directions')
    op.drop_index(op.f('ix_plan_directions_created_by_user_id'), table_name='plan_directions')
    op.drop_index(op.f('ix_plan_directions_created_at'), table_name='plan_directions')
    op.drop_index('ix_plan_directions_active_sort', table_name='plan_directions')
    op.drop_table('plan_directions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_staff_member_id'), table_name='users')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_region_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_iin'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('school_staff_roles')
    op.drop_index('ix_staff_school_id', table_name='school_staff_members')
    op.drop_index('ix_staff_iin', table_name='school_staff_members')
    op.drop_index(op.f('ix_school_staff_members_school_id'), table_name='school_staff_members')
    op.drop_index(op.f('ix_school_staff_members_qualification_order_date'), table_name='school_staff_members')
    op.drop_index(op.f('ix_school_staff_members_ped_start_date'), table_name='school_staff_members')
    op.drop_index(op.f('ix_school_staff_members_is_active'), table_name='school_staff_members')
    op.drop_table('school_staff_members')
    op.drop_index(op.f('ix_schools_settlement'), table_name='schools')
    op.drop_index(op.f('ix_schools_district_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_districts_region_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
